In [1]:
# サンプル2-03
10 + 2

12

In [2]:
# サンプル2-04-1
a = 10      # 変数aに10を代入
a - 6       # aから6を減算

4

In [3]:
a

10

In [4]:
# サンプル2-04-2
a = 10      #変数aに10を代入
a = a - 6   # a - 6の結果をaに再代入する
print(a)    # aを出力

4


In [5]:
# サンプル2-05-1
number = [1, 2, 3, 4, 5]
print(number)    # 出力

[1, 2, 3, 4, 5]


In [6]:
# サンプル2-05-2
data = ['身長', 160, '体重', 40.5]
print(data)    # 出力

['身長', 160, '体重', 40.5]


In [7]:
# サンプル2-05-3
x = [1, 2, 3, 4, 5]
print(x)      # リストの中身を出力

[1, 2, 3, 4, 5]


In [8]:
len(x)        # リストの長さ（要素の数）を取得

5

In [9]:
x[0]        # 最初の要素にアクセス

1

In [10]:
x[4] = 100  # 5番目の要素を変更する
print(x)

[1, 2, 3, 4, 100]


In [11]:
# サンプル2-06-1
import numpy as np
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [12]:
# サンプル2-06-2
x[0]         # 1つ目の要素を参照

1

In [13]:
x[2] = 100   # 3番目の要素を100に変更する
print(x)

[  1   2 100]


In [14]:
# サンプル2-06-3
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y            # 要素ごとの足し算

array([5, 7, 9])

In [15]:
x - y            # 要素ごとの引き算

array([-3, -3, -3])

In [16]:
x * y            # 要素ごとの掛け算

array([ 4, 10, 18])

In [17]:
x / y            # 要素ごとの割り算

array([0.25, 0.4 , 0.5 ])

In [18]:
# サンプル2-06-4
x = np.array([1, 2, 3, 4, 5], dtype = float)   # dtypeで明示的に型を指定
print(x)

[1. 2. 3. 4. 5.]


In [19]:
x + 10

array([11., 12., 13., 14., 15.])

In [20]:
x - 1

array([0., 1., 2., 3., 4.])

In [21]:
x * 10

array([10., 20., 30., 40., 50.])

In [22]:
x / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [23]:
# サンプル2-06-5
x = np.array([1, 2, 3, 4, 5], dtype = float)
np.power(x, 2)

array([ 1.,  4.,  9., 16., 25.])

In [24]:
x ** 2

array([ 1.,  4.,  9., 16., 25.])

In [25]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])